# Generated by Django 5.0.2 on 2024-02-07 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Uqituvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=250)),
                ('famila', models.CharField(max_length=255)),
                ('yonalishi', models.CharField(max_length=255)),
                ('yoshi', models.IntegerField()),
                ('Tugilgan_yili', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dars_nomi', models.CharField(choices=[('Ona_tili', 'Ona_tili'), ('Matematika', 'Matematika'), ('Tarix', 'Tarix'), ('Adibiyot', 'Adabiyot')], max_length=250)),
                ('uqituvchi', models.CharField(max_length=255)),
                ('kirish_vaqti', models.DateTimeField()),
                ('chiqish_vaqti', models.DateTimeField()),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.name')),
            ],
        ),
    ]
