# Generated by Django 5.0.2 on 2024-02-07 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uqituvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uqituvchi'),
        ),
    ]
